sites:
  - MYNTRA
  - AJIO
  - KOOVS
  - AJIO-TRENDS
  - ASOS

verticals:
  - men_tshirts
  - men_casual_shirts
  - women_western_dress
  - women_tops_tshirts
  - women_jumpsuits
  - women_ethnic_dress